import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

let version = 'dev';

try {
  version = execSync('git rev-parse --short=8 HEAD', { encoding: 'utf8' }).trim();
} catch {
  // Falls back to "dev" when git metadata is unavailable.
}

const versionFilePath = path.resolve(process.cwd(), 'src', 'version.ts');
writeFileSync(
  versionFilePath,
  `// This file is auto-generated by scripts/generate-version.mjs - do not edit manually\nexport const APP_VERSION = '${version}';\n`
);
