import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

let version = 'dev';

try {
  const gitHash = execSync('git rev-parse --short=8 HEAD', { encoding: 'utf8' }).trim();
  if (/^[0-9a-f]{1,40}$/i.test(gitHash)) {
    version = gitHash;
  } else {
    console.warn('Invalid git hash format, using dev version');
  }
} catch {
  console.warn('Git metadata unavailable, using dev version');
}

const versionFilePath = path.resolve(process.cwd(), 'src', 'version.ts');
writeFileSync(
  versionFilePath,
  `// This file is auto-generated by scripts/generate-version.mjs - do not edit manually\nexport const APP_VERSION = '${version}';\n`
);
